import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { Script } from "node:vm";
const root = new URL("../", import.meta.url);
const manifest = JSON.parse(await readFile(new URL("package.json", root), "utf8"));
const core = (await readFile(new URL("src/core.js", root), "utf8")).replace(/^export /gm, "");
const client = (await readFile(new URL("src/client.js", root), "utf8")).replace(/^export /gm, "");
const bundle = `// Generated by scripts/build.mjs; edit src/, not this bundle.
window.__ModuleLoader__.load({
  id: ${JSON.stringify(manifest.name)},
  factory(require) {
    const React = require("react");
${core}
${client}
    const plugin = createClientPlugin(React);
    return { ...plugin, default: plugin };
  },
});
`;
new Script(bundle, { filename: "client.js" });
await mkdir(new URL("lib/", root), { recursive: true });
await writeFile(new URL("lib/client.js", root), bundle);
console.log("Built " + fileURLToPath(new URL("lib/client.js", root)));
